[package]
name = "sovrin-client"
version = "0.1.0"
authors = [
  "Sergej Pupykin <sergej.pupykin@dsr-company.com>",
  "Vyacheslav Gudkov <vyacheslav.gudkov@dsr-company.com>",
  "Artem Ivanov <artem.ivanov@dsr-company.com>",
  "Evgeniy Razinkov <evgeniy.razinkov@dsr-company.com.ru>",
  "Kirill Neznamov <kirill.neznamov@dsr-company.com>",
  "Sergey Minaev <sergey.minaev@dsr-company.com>"
  ]

description = "Sovrin client with c-callable interface"
license = "MIT/Apache-2.0"

[lib]
name = "libsovrin"
path = "src/lib.rs"

[[bin]]
name = "sovrin"
path = "src/main.rs"

[dependencies]
int_traits = "0.1.1"
env_logger = "0.4.2"
libc = "0.2.21"
log = "0.3.7"
openssl = "0.9.9"
milagro-crypto = { git = "https://github.com/DSRCorporation/milagro-crypto-rust" }
rand = "0.3"
rusqlite = "0.10.1"
rust-base58 = "0.0.4"
rustc-serialize = "0.3"
sodiumoxide = "0.0.14"
zmq = "0.8.1"
lazy_static = "0.2"
