version: '2'
services:
  sovrin-client-rust-test:
    build:
      context: .
      dockerfile: ci/ubuntu.dockerfile
    command: cargo test --color=always
    volumes:
      - ".:/home/sovrin/sovrin-client-rust"
    working_dir: /home/sovrin/sovrin-client-rust