[package]

name = "watermark"
version = "0.0.1"
authors = [ "Mark Hadley <mark.hadley@evernym.com>" ]

[lib]
name = "cxs"
path = "src/lib.rs"

[dependencies]
indy = { path = "/home/mark/dev/indy-sdk/libindy/" }
lazy_static = "0.2"
